export const FETCH_VENUES_REQUEST = "FETCH_VENUES_REQUEST";
export const FETCH_VENUES_SUCCESS = "FETCH_VENUES_SUCCESS";
export const FETCH_VENUES_FAILURE = "FETCH_VENUES_FAILURE";

export const GET_CLIENT_LOCATION_REQUEST = "GET_CLIENT_LOCATION_REQUEST";
export const GET_CLIENT_LOCATION_SUCCESS = "GET_CLIENT_LOCATION_SUCCESS";
export const GET_CLIENT_LOCATION_FAILURE = "GET_CLIENT_LOCATION_FAILURE";
